name = "match107/learning"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'match107/learning'"

[repository]
user = "match107"
project = "learning"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
